// Countries Actions
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRIES_BY_NAME = "GET_COUNTRIES_BY_NAME";
export const SORT_BY_ABC = "SORT_BY_ABC";
export const SORT_BY_POPULATION = "SORT_BY_POPULATION";
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const FILTER_PAGE = "FILTER_PAGE";

// Activities Actions
export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES";
export const POST_NEW_ACTIVITY = "POST_NEW_ACTIVITY";
export const REMOVE_ACTIVITY = "REMOVE_ACTIVITY";
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";
/* export const FETCH_ACTIVITY = "FETCH_ACTIVITY"; */
